<?php
/**
 * Head.phtml Heading
 */
?>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="HandheldFriendly" content="True" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="address=no" />

<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<!-- Fcaebook Open Graph Tags -->
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getGroup()->getName(); ?>" />
<meta property="og:title" content="<?php echo $this->getTitle() ?>"/>
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl() ?>" />
<meta property="og:description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<!-- page ID should go here
<meta property="fb:page_id" content="" />
-->
<?php 
// ***** Detect CMS page 
if(Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ):
?>
<meta property="og:image" content="<?php echo  $this->getSkinUrl() . Mage::getStoreConfig('design/header/logo_src'); ?>"/>
<?php endif; ?>

<?php 
// ***** Category page 
if (Mage::registry('current_category')) : 
$ogTitle = Mage::registry('current_category')->getName();
$_category  = Mage::registry('current_category');
$cur_category = Mage::getModel('catalog/category')->load($_category->getId());
$imageUrl = $cur_category->getImageUrl();
?>
<meta property="og:image" content="<?php echo $imageUrl;?>" />

<?php endif;?>

<?php 
// ***** Product page 
if (Mage::registry('current_product')) : 
$product= Mage::getModel('catalog/product')->load(Mage::registry('current_product')->getId());
$price = $product->getPrice();
$webprice = $product->getwebprice();
$specialprice = $product->getFinalPrice();
	if($specialprice==$price):
		$printprice = number_format($price,2);	
	else:
		$printprice = number_format($specialprice,2);	
	endif;
?>
<meta property="og:type" content="og:product" />
<meta property="og:image" content="<?php echo Mage::helper('catalog/image')->init(Mage::registry('current_product'), 'small_image')->resize(200,200);?>" />
<meta property="product:price:amount" content="<?php echo $printprice ?>" />
<meta property="product:price:currency" content="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?> "/>
<?php endif;?>
<!-- Fcaebook Open Graph Tags Ends -->


<!-- apple-touch-icons -->
<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<link rel="apple-touch-icon-precomposed" href="<?php echo  $this->getSkinUrl() . Mage::getStoreConfig('design/header/logo_src'); ?>" />
<!-- For first- and second-generation iPad: -->
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo  $this->getSkinUrl() . Mage::getStoreConfig('design/header/logo_src'); ?>" />
<!-- For iPhone with high-resolution Retina display: -->
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo  $this->getSkinUrl() . Mage::getStoreConfig('design/header/logo_src'); ?>" />
<!-- For third-generation iPad with high-resolution Retina display: -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo  $this->getSkinUrl() . Mage::getStoreConfig('design/header/logo_src'); ?>" />

<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="apple-mobile-web-app-title" content="" />

<!-- Windows 8 Tiles -->
<meta name="application-name" content="<?php echo $this->getTitle() ?>" />
<meta name="msapplication-TileImage" content="<?php echo  $this->getSkinUrl("images/icon-114-precomposed.png"); ?> " />
<meta name="msapplication-TileColor" content="#ffffff" />

<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="cleartype" content="on" />
<![endif]-->

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>!window.jQuery && document.write(unescape('%3Cscript src=""<?php echo $this->getSkinUrl('js/jquery.min.js'); ?>"%3E%3C/script%3E'))</script>
<script>
  $.noConflict();
</script>
<?php echo $this->getCssJsHtml() ?>
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src=""<?php echo $this->getSkinUrl('js/respond.min.js'); ?>"%3E%3C/script%3E'))</script>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src=""<?php echo $this->getSkinUrl('js/html5.js'); ?>"%3E%3C/script%3E'))</script>
<![endif]-->
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

